id: P54856EDB
initial_creation_type: input
source_metadata:
  Title: Marmakālikā
  Editor: Janardan Shastri
  Publisher: Tattvajnanasiddhi including Marmakalikapanjika Sahita
  Place of Publication: Sarnath, Varanasi, India
  Year: '2000'
  1 āśīrvādābhidhānam:
    Text Version: ''
    Input Personnel: ''
    Input Date: ''
    Proof Reader: ''
    Supplier: ''
    Sponsor: ''
  2 bāhyārcanavidhiḥ:
    Text Version: ''
    Input Personnel: ''
    Input Date: ''
    Proof Reader: ''
    Supplier: ''
    Sponsor: ''
  3 bhāvanāvidhiḥ:
    Text Version: ''
    Input Personnel: ''
    Input Date: ''
    Proof Reader: ''
    Supplier: ''
    Sponsor: ''
  4 śiṣyānugrahavidhiḥ:
    Text Version: ''
    Input Personnel: ''
    Input Date: ''
    Proof Reader: ''
    Supplier: ''
    Sponsor: ''
  5 mantroddhāravidhiḥ:
    Text Version: ''
    Input Personnel: ''
    Input Date: ''
    Proof Reader: ''
    Supplier: ''
    Sponsor: ''
  6 pūjāvidhiḥ:
    Text Version: ''
    Input Personnel: ''
    Input Date: ''
    Proof Reader: ''
    Supplier: ''
    Sponsor: ''
  7 balividhiḥ:
    Text Version: ''
    Input Personnel: ''
    Input Date: ''
    Proof Reader: ''
    Supplier: ''
    Sponsor: ''
  8 japavidhiḥ:
    Text Version: ''
    Input Personnel: ''
    Input Date: ''
    Proof Reader: ''
    Supplier: ''
    Sponsor: ''
  9 samayaparipālanavidhiḥ:
    Text Version: ''
    Input Personnel: ''
    Input Date: ''
    Proof Reader: ''
    Supplier: ''
    Sponsor: ''
created_at: '2022-03-08T16:57:53.618939'
last_modified_at: '2022-03-08T16:57:53.618952'
